name: Build and Test simple device module with latest openDAQ release 

on:
  push:
    branches: [main]
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  test-asset:
    permissions:
      contents: read
      actions: read

    # env:
    #   GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout simple device module repo
        uses: actions/checkout@v4

      - name: Install openDAQ framework
        uses: openDAQ/actions/install-framework@jira/TBBAS-2871-download-and-install-sdk

      - name: Build and test simple device module
        uses: ./.github/actions/module-build-test
