name: Build and Test simple device module with latest openDAQ release 

on:
  push:
    branches: [main]
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  test-asset:
    permissions:
      contents: read
      actions: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            enable-32bit: false
          - os: windows-latest
            enable-32bit: false
          - os: windows-latest
            enable-32bit: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout simple device module repo
        uses: actions/checkout@v4

      - name: Install openDAQ framework
        uses: openDAQ/actions/install-framework@jira/TBBAS-2871-download-and-install-sdk
        with:
          enable-32bit: ${{ matrix.enable-32bit }}

      - name: Build and test simple device module
        uses: ./.github/actions/module-build-test
        with:
          enable-32bit: ${{ matrix.enable-32bit }}
